### ISSUE TITLE
Header checking and cpu usage

### ISSUE THREAD

**Issue by peaveyman** [demanuel/NewsUP#51] opened 2017-08-19 09:43 UTC
Newsup doesn't use much cpu until it gets to the header checking portion of the upload. Sometimes my temp will get close to the critical stage while this is happening. Any idea why this might be happening?

**Comment by demanuel** [comment] 2017-08-20 20:15
Only sometimes? That sounds like a bug... :-(

Can you reproduce it? How big is the upload, how many connections are you using?

**Comment by peaveyman** [comment] 2017-08-20 20:21
It is hit and miss in when it will do it. The upload size is usually around
200 to 500 megabytes.

**Comment by demanuel** [comment] 2017-09-04 22:37
What version are you using? Are you using the version in the master branch or the version in the with_id branch?

**Comment by demanuel** [comment] 2017-09-06 22:01
Can you check the latest version of master branch?

**Comment by peaveyman** [comment] 2017-09-09 22:30
I'm testing it now.

**Comment by demanuel** [comment] 2017-09-10 00:27
Sorry, my fault. I didn't tested it, as my account expired. That error should be fixed by now.

Can you try again?

**Comment by peaveyman** [comment] 2017-09-10 01:19
I'm trying but now get this error: Please configure all the required inputs server,port,username,password, newsgroups

**Comment by demanuel** [comment] 2017-09-10 07:55
In your newsup.conf, change the option from "newsgroup" to "newsgroups"

**Comment by peaveyman** [comment] 2017-09-10 10:15
It's posting now but I am getting this message after every piece is
posted: Warning:
Read after posting article: 240 Article Posted

I will let you know about the cpu usage during the header check shortly.

**Comment by demanuel** [comment] 2017-09-10 10:20
That's because of issue #42

**Comment by peaveyman** [comment] 2017-09-10 10:27
The header checked worked great. No ramping up of the cpu or anything.
Seems that issue can be closed.

**Comment by demanuel** [comment] 2017-09-10 10:28
nice :-)

**Closed by demanuel** 2017-09-10 10:28 UTC

**Comment by peaveyman** [comment] 2017-09-10 10:31
Thanks for the work on this.
