### ISSUE TITLE
can't check nzb files

### ISSUE THREAD

**Issue by theckld** [demanuel/NewsUP#91] opened 2020-08-27 03:43 UTC
While trying to check nzb files using ``` newsup --check my_file.nzb ``` I'm getting this error:
```
http://www.hokkaidohotelsjapan.com/newzbincom/:1: parser error : Content error in the external subset
<!DOCTYPE html>
^
http://www.hokkaidohotelsjapan.com/newzbincom/:1: parser error : Content error in the external subset
<!DOCTYPE html>
^
```
I'm not sure which file is it trying to read because my nzb does not have this weird url ""http://www.hokkaidohotelsjapan.com/newzbincom" in its contents but instead I have, as usual, the following:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
```

**Comment by demanuel** [comment] 2020-08-27 17:37
Can you remove the doctype? the XML schema is downloaded to validate the XML and the newzbin domain isn't valid anymore.


https://en.wikipedia.org/wiki/XML_schema#Validation

I will try to disable the schema validation.


A August 27, 2020 3:44:04 AM UTC, theckld <notifications@github.com> escreveu:
>While trying to check nzb files using ``` newsup --check my_file.nzb ``` I'm getting this error:
>```
>http://www.hokkaidohotelsjapan.com/newzbincom/:1: parser error : Content error in the external subset
><!DOCTYPE html>
>^
>http://www.hokkaidohotelsjapan.com/newzbincom/:1: parser error : Content error in the external subset
><!DOCTYPE html>
>^
>```
>I'm not sure which file is it trying to read because my nzb does not have this in its contents "http://www.hokkaidohotelsjapan.com/newzbincom", but instead I have, as usual, the following:
>```
><?xml version="1.0" encoding="utf-8"?>
><!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
><nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/demanuel/NewsUP/issues/91
-- 
Sent from my phone with K-9 Mail. Please excuse my brevity.

**Comment by demanuel** [comment] 2020-08-29 22:28
I'm not able to reproduce it in the latest version.

Are you trying with the latest version? If so can you send me the NZB and it's checksum?

**Comment by demanuel** [comment] 2020-09-02 21:52
BTW, if you use usenet.farm they had a problem with the head command. They fixed the error today.

**Comment by demanuel** [comment] 2020-09-19 13:11
Closing it as there's no update. Feel free to re-open it.

**Closed by demanuel** 2020-09-19 13:11 UTC
