### ISSUE TITLE
Enhancement: multi-thread the header check

### ISSUE THREAD

**Issue by kouze** [demanuel/NewsUP#22] opened 2015-10-17 13:26 UTC
Hi,

header-check is really useful, unfortunately using a single thread today, which is slowing down A LOT the full upload.
Would it be possible to multi-thread it like you did for the post process?

Thanks

**Comment by demanuel** [comment] 2015-10-17 16:45
It's on my TODO list.

Unfortunately, there are still more urgent issues :-(

**Comment by demanuel** [comment] 2015-10-29 10:36
@kouze 

Can you check the v3 branch, and check if it's better?
It's a release candidate, so bugs may exist :-)

**Comment by kouze** [comment] 2015-10-29 16:21
Hi,

i'll test that today :)

Thanks

**Comment by kouze** [comment] 2015-10-29 17:55
Hi,

well it's seem that it's not working.
Without touching anything the process is "blocked" after Operation completed. I guess the wait(); at line 388 is for something.
If I comment this line, the process blocks after Warping up engines! but I did not debug enough to find the root cause.

Thanks

**Comment by demanuel** [comment] 2015-10-29 18:02
The wait is to finish the read process. You shouldn't comment that!

The header check only starts after the "warping engines!" message, because the header check is done after the upload and not during the upload.

What do you mean blocks after the warming up engines? Are you sure it's not doing the headercheck? Can you wait for some time?

**Comment by kouze** [comment] 2015-10-29 18:16
Hi,

this is the output of the master branch. You will note that you don't have the wait(); in that branch after the post and before the header check:

time perl ~/bin/NewsUP_old/newsup.pl -f 9bde364f8adced06493979f74c766f86 -nzb toto.nzb
Splitting files per connection
Launching upload process (706 segments)
.........[...]...
Launching header check on server reader2.newsxs.nl:119
.........[...]...
Found 2 missing segments!
Launching upload process (2 segments)
..Error: Post failed: 437 Rejected (435 <181446141991782808.ARH51LU4OM@E8M4GJMLJS.newsup>).

Launching header check on server reader2.newsxs.nl:119
..
Found 0 missing segments!
Upload Finished!
Transfered 510MB in 1m 54s. Speed with header check: [4584 KBytes/Sec]
NZB toto.nzb created!

real    1m53.608s
user    0m6.811s
sys     0m0.766s


This is the same with v3 branch (I put back the wait();):

time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86 -nzb toto.nzb
Operation completed 510MB in 0m 8s. Speed: [65323 KBytes/Sec]
^C

real    3m8.710s
user    0m2.719s
sys     0m0.653s

I cancelled the process after 3m waiting to have the header check starting. So I don't know what the wait() is waiting for, but I guess it will wait forever :)

Thanks

**Comment by demanuel** [comment] 2015-10-29 18:50
That's very odd! What platform are you using? (i can see that's *nix based. It's risc os?)
The wait is to "wait" for the child process to finish - It needs to close the connections. 
It shouldn't take 3 minutes. That's for sure.

Can you go to line 563 and uncomment the line, run it, and paste the last output you get ?

While it's stuck, can you do a:
* ps xua | grep -i perl
* netstat -a | grep -i nntps


p.s.: Holy shit. How much upload you have? :-O

**Comment by kouze** [comment] 2015-10-29 19:00
Hi,

the box is a simple ubuntu, x86_64 (kernel 3.13)

Here is the last output (lots of thanks! and try me! :):

[340 Try Me!]
[340 Try Me!]
Operation completed 510MB in 0m 7s. Speed: [74655 KBytes/Sec]
[240 Thanks!]
[340 Try Me!]
[340 Try Me!]
[205 Exit articles 0, bytes 0, groups 0, posts 27, postbytes 32491609]
[240 Thanks!]
[205 Exit articles 0, bytes 0, groups 0, posts 15, postbytes 24568998]
[340 Try Me!]
[240 Thanks!]
[205 Exit articles 0, bytes 0, groups 0, posts 26, postbytes 36455442]
[240 Thanks!]
[240 Thanks!]
[340 Try Me!]
[340 Try Me!]
[340 Try Me!]
[240 Thanks!]
[340 Try Me!]

ps xua | grep -i perl
nykouze  30651  1.9  3.4 625404 562456 pts/17  S+   19:54   0:03 perl /home/nykouze/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
nykouze  30658  6.8  0.1  82976 16812 pts/17   R+   19:54   0:11 perl /home/nykouze/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86

netstat -a | grep -i nntps return nothing while stuck (same for nntp)

Info: I'm using this setup:
[server]
server= reader2.newsxs.nl
port= 119
connections= 15

(no ssl)

and yEncBin <yEncBin@Poster.com> is not only me (but I uploaded few things since more than 3 years now ;p)

Thanks

**Comment by demanuel** [comment] 2015-10-29 19:22
welll... the info is contradictory... You see, you have 15 connections, there's only 3 exits (code 205) and there's only one process running (which confirms the netstat command)... 

Did you got only 3 codes 205 ?

hmmm...  Can you comment the line 392, just to be sure that it's not getting stuck on the sleep.

Can you also paste here the settings for the headercheck?

I have no clue... :-P

I guess i'll need to create a ubuntu VM

**Comment by kouze** [comment] 2015-10-29 21:31
So, I changed the config to use only 1 connection. Here is the log:

time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
[340 Try Me!]
[340 Try Me!]
[240 Thanks!]
[340 Try Me!]
[240 Thanks!]
[340 Try Me!]
[240 Thanks!]
[340 Try Me!]
[240 Thanks!]
[340 Try Me!]
[240 Thanks!]
[340 Try Me!]
[240 Thanks!]
[340 Try Me!]
Operation completed 510MB in 0m 17s. Speed: [30740 KBytes/Sec]

so here no exits anymore.
I ran the program with line 392 commented, no changes as it didn't reach it (else we would have seen Header Checking)

Here is the config of the headercheck:
[headerCheck]
enabled= 1
sleep= 30
retries= 3

In fact there is something in netstat, but I needed to check the port directly (instead of nntp)
 netstat -an | grep ":119"
tcp        1      0 XXX:35941     91.223.220.11:119       CLOSE_WAIT
tcp        0      0 XXX:35942     91.223.220.11:119       CLOSE_WAIT

I just removed my server ip ;)
reader2.newsxs.nl has address 91.223.220.11

So yes, the connection is not closed properly (and why 2 connections while I asked for one only?)

Thanks

**Comment by kouze** [comment] 2015-10-29 22:14
The thing is in this v3 version, you never close the socket?

in the master branch you are doing:

_print_args_to_socket ($socket, "quit", $CRLF);
_read_from_socket($socket);
shutdown $socket, 2;

but in the V3 version, you only do:

_print_args_to_socket($_, "QUIT", $CRLF) for @$connectionList;

so maybe something missing here?

**Comment by demanuel** [comment] 2015-10-29 22:33
So, i guess i found out the problem. The issue is in the server. Let me explain:

'''
The CLOSE_WAIT status indicates that the server has received the first FIN signal from the client and the connection is in the process of being closed. So this essentially means that his is a state where socket is **waiting for the application** to execute close(). **A socket can be in CLOSE_WAIT state indefinitely until the application closes it.** 
'''
(from http://blogs.technet.com/b/janelewis/archive/2010/03/09/explaining-close-wait.aspx ).
 - the bold is mine.


This means that I send the quit command to the server. But the server instead of replying a 205 code, is just closing the TCP connection. Since i never get a 205, i will never close the connection on the application side. That's the reason it gets stuck.
This explanation fits in all the scenarios you posted.

So the problem is on the server side - they should follow NNTP standards. Can you please send them an email? :-)

Meanwhile i'm going to find a solution for this on the application side.

The reason it appears two entries on the netstat output is because you only have one connection. Makes sense right? The netstat uses the file descriptor table to find the connections, and when there is a fork, all the FDs from a process are duplicated. The way i'm implemented this version was to have completely async read/write processes and to achieve that i have to fork one of the processes (either write or read but in this case is only read) so you have only one process for reading and only one process for posting.

Thanks for your help.

**Comment by kouze** [comment] 2015-10-30 14:14
Oh OK, good to hear. At least it's not my system.
I will give a try with another server today or tomorrow and let you know the result.

**Comment by demanuel** [comment] 2015-10-31 18:28
Can you try the last v3 branch?

**Comment by kouze** [comment] 2015-11-01 14:10
Hi,

no change with my server. The process still stops after "Operation completed" (because of the wait()) and socket is still opened:
Netstat after 2 min waiting:
netstat -an | grep ":119"
tcp        0      0 195.154.171.8:60651     91.223.220.11:119       ESTABLISHED
tcp        0      0 195.154.171.8:60652     91.223.220.11:119       CLOSE_WAIT

Thanks

**Comment by demanuel** [comment] 2015-11-08 18:12
Hi Kouze, 

I've been busy, but can you test the last commit of the v3 branch?

Thx.

**Comment by kouze** [comment] 2015-11-12 17:20
Hi,

sorry for my late response.

this is still not working :)

time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
Operation completed 510MB in 0m 41s. Speed: [12746 KBytes/Sec]
^C
real    23m40.100s
user    0m3.997s
sys     0m0.894s

I waited much more time this time.

Thanks

**Comment by demanuel** [comment] 2015-11-16 14:01
Can you check the latest version. I'm sending a SIGTERM to the read process so it doesn't get hanged - the read process catches it and then proceeds accordingly. If it doesn't work... Well a SIGKILL is my last option...

**Comment by kouze** [comment] 2015-11-17 18:04
Hi,

there are some progress :) unfortunately now the process is stopped after "Warping up engines!"

 time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
Operation completed 510MB in 0m 8s. Speed: [65323 KBytes/Sec]
Header Checking
Warping up engines!
^C
real    3m42.323s
user    0m4.332s
sys     0m0.826s

I don't even know if the program has started the header check...

Thanks

**Comment by demanuel** [comment] 2015-11-17 18:46
I like progress! :-D

Can you add on line 429 (https://github.com/demanuel/NewsUP/blob/ee3f15fe68798b2d64cd63ea82a0ec225590fd8a/newsup.pl#L429) the following code:

```perl
say $output;
```

and uncomment line 415 (just remove the # before the say) and report back?

Cheers!

**Comment by demanuel** [comment] 2015-11-19 14:49
@kouze , Can you check the latest commit in V3 ?

Now the headercheck produces output (or at least it should). You'll also need to change the conf file and add the option connections in the configuration file.

**Comment by kouze** [comment] 2015-11-22 18:13
Hi,

headercheck is now working but:
1. extremely slow - the check using 3 connections and taking lot's more time than the upload itself
2. provide "incorrect" results, like lots of segment missing (I guess all of them?) which is not expected. I upload already files using newsmangler and I don't have bad results (most of my upload are 100% complete)

Here is my setup:
cat ~/.config/newsup.conf
[server]
server= reader2.newsxs.nl
port= 119
connections= 1

[auth]
user= myuserid
password= mypassword

[metadata]
#client= NewsUP

[upload]
uploader= yEncBin <yEncBin@Poster.com>
newsgroup= alt.binaries.test

[headerCheck]
enabled= 1
sleep= 30
retries= 1
connections = 3

So I'm using 1 connection for the upload, and 3 connections for the headercheck.
I changed the retries from 3 to 1 because of the speed of the headercheck. I want to provide some timings on how much time the headercheck is taking

Here is the log:
time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
Operation completed 510MB in 0m 7s. Avg. Speed: [74655 KBytes/Sec]
Warping up header check engines with 3 connections!
There are 706 segments missing!
There are 706 segments missing!
HeaderCheck done in 18m 17s
NZB newsup.nzb created!

real    18m54.189s
user    0m10.396s
sys     0m2.139s

So 18min of headerchecking for an upload that took 7 sec is a little too much :)

Possible issues are:
1. the upload is not done properly, which then would explain why all segments are missing and why the headercheck is taking so much time. I guess when a segment is missing, the process is taking more time.
2. the 30 sec sleep is not enough to wait between the upload and the headercheck. But I already tested this in the past, and 30 sec were enough (upload and headercheck are done on the same server)
3. headercheck is not working as expected

The .nzb generated contains some data. I tries to download it after 30 min and yes, nothing was available :(
you can get the .nzb here: http://s000.tinyupload.com/index.php?file_id=83565768684398428486

So I tried the master branch:
time perl ~/bin/NewsUP_old/newsup.pl -f 9bde364f8adced06493979f74c766f86
Splitting files per connection
Launching upload process (706 segments)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++All connections finished!
Operation completed 510MB in 0m 58s. Speed: [9010 KBytes/Sec]

Launching header check on server reader2.newsxs.nl:119
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Found 0 missing segments!
Upload Finished!
Total Time: 2 m 16s
NZB newsup.nzb created!

real    2m17.971s
user    0m6.988s
sys     0m1.173s

The upload is clearly slower, but the headercheck worked. So I guess the upload itself worked as well.

Which would mean that v3 is failing already when uploading data to usenet server.

Thanks,

**Comment by demanuel** [comment] 2015-11-22 23:00
If 706 segments are missing then it's because all the uploaded segments failed (if you didn't changed the segment size: 706*750KBytes = 517MB). Also the speed difference (from 74MBytes/second to 9 MBytes/s) between the branch and the master shows that something in the upload failed... 

Maybe this is the reason. The uploader email needs to be between '<' and '>'.
So it should be:
```
uploader= yEncBin <yEncBin@Poster.com>
```

BTW, are you sure you have the latest commit - RC5? 

My connections sucks but when i run:
```text
Operation completed 836MB in 15m 9s. Avg. Speed: [942 KBytes/Sec]
Warping up header check engines with 4 connections!
There are 0 segments missing!
HeaderCheck done in 1m 44s
NZB new_test.nzb created!
```

**Comment by kouze** [comment] 2015-11-23 09:00
Hi,

the uploader email is correct, the < > were removed by github :)

```
[upload]
uploader= yEncBin <yEncBin@Poster.com>
newsgroup= alt.binaries.test
```

In fact I'm using the same config file for both master and v3 branch.

And I'm on the latest version on both branch.

Would it be possible to get some log regarding the upload? 
The upload speed is really strange, too fast with only 1 connection. So yes I guess there is an issue here.

Thanks

**Comment by kouze** [comment] 2015-11-23 14:44
Hi,

I played a little bit with the number of connections for the main upload, and this is the result:

1 connection:
```
time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
Operation completed 510MB in 0m 9s. Avg. Speed: [58065 KBytes/Sec]
Warping up header check engines with 3 connections!
There are 706 segments missing!
There are 706 segments missing!
HeaderCheck done in 17m 39s
NZB newsup.nzb created!

real    18m17.880s
user    0m9.931s
sys     0m2.090s
```

2 connections:
```
time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
Operation completed 510MB in 0m 15s. Avg. Speed: [34839 KBytes/Sec]
Warping up header check engines with 3 connections!
There are 672 segments missing!
There are 632 segments missing!
HeaderCheck done in 17m 0s
NZB newsup.nzb created!

real    17m46.099s
user    0m8.867s
sys     0m1.735s
```

3 connections:
```
time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
Operation completed 510MB in 0m 8s. Avg. Speed: [65323 KBytes/Sec]
Warping up header check engines with 3 connections!
There are 646 segments missing!
There are 561 segments missing!
HeaderCheck done in 15m 27s
NZB newsup.nzb created!

real    16m5.816s
user    0m8.076s
sys     0m1.568s
```

So the more connections I'm using, the less segments are missing.
Could you check on your side using only 1 connection for the upload?

Thanks

**Comment by demanuel** [comment] 2015-11-30 17:00
Hi Kouze.

Thanks for the analysis.

I tried with one connection and realized that for some reason i started getting status code 500. Not sure why... Anyway, i'm capturing that output now.

Can you please test the last version? RC6

**Comment by demanuel** [comment] 2015-12-11 19:16
Hi Kouze,

I don't have a solution for this.... I can't figure it out what's happening, why the connection dies... This issue seems to be confined to xsnews, as i'm unable to reproduce it and all the reports i have are on xsnews.

I'm leaving this issue open although i don't have any solution for this... Yet!

This is an issue without ETA.

**Comment by kouze** [comment] 2016-01-07 15:46
Hi Demanuel,

I checked your latest master version I this version is working far much better than the old V3 I tested.
The upload is working fine, but still a small issue :)
It seems that the upload is failing when reaching the end of the upload

I tried to upload the same directory (so list of files) multiple times, and each time all files where 100% available except the last one where few articles were missing.

```
~/bin/NewsUP/scripts/completion_checker.pl -nzb newsup.nzb | grep completed
File 9bde364f8adced06493979f74c766f86.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part01.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part02.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part03.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part04.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part05.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part06.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part07.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part08.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part09.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.sfv is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol00+01.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol01+02.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol03+04.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol07+08.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol15+16.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol31+32.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol63+28.par2 is 86.206897% completed
```
This upload has been done using 10 connexions.

Even when using only 1 connexion for the upload, the last file still miss one article:
```
~/temp/toto$ ~/bin/NewsUP/scripts/completion_checker.pl -nzb newsup.nzb | grep completed
File 9bde364f8adced06493979f74c766f86.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part01.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part02.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part03.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part04.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part05.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part06.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part07.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part08.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part09.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.sfv is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol00+01.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol01+02.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol03+04.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol07+08.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol15+16.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol31+32.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol63+28.par2 is 96.551724% completed
```

```
223 0 <261452181290168674.BY561K5WMP@EAR6VHYFS2.newsup>
223 0 <271452181290168688.L0OVOIYFU@EAR6VHYFSG.newsup>
223 0 <281452181290168702.5310QY59RZ@EAR6VHYFSU.newsup>
430 No such article.
File 9bde364f8adced06493979f74c766f86.vol63+28.par2 is 96.551724% completed
```

Would it be possible that "something" is missing in your code trying to "close" the socket or something too soon?

Thanks :)

**Comment by demanuel** [comment] 2016-01-07 19:43
Thanks for your analysis. I'm going to take a look.
Some questions:

1- Is the headercheck enabled during the upload? If yes does it complain about missing segments?
2- Are you headerchecking on the same server that you uploaded? Or you are uploading to a server and checking on other?
3- Your header check is done how much time after the upload?
4- Can you provide me a NZB? 
5- How's the speeds?

I guess that's it, for now. I'll check if i find something.

**Comment by kouze** [comment] 2016-01-08 09:26
Hello,

* 1) no, for this specific test I removed the header check. When enabled, yes it complains about missing segments and try to repost the missing ones. Unfortunately, even after the headercheck (with 1 retry), there are still missing segments (and always at the end of the upload).

example:
```
time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
Operation completed 510MB in 0m 9s. Avg. Speed: [58065 KBytes/Sec]
Warping up header check engines with 10 connections!
There are 2 segments missing
HeaderCheck done in 0m 36s
NZB newsup.nzb created!

real    0m45.462s
user    0m3.991s
sys     0m1.012s
```

* 2) headercheck on the same server than the upload
* 3) 30 sec. Even after 1h the result is the same
* 4) You will find different .nzb:
 * First one is an upload done using 1 thread without headercheck: https://mega.nz/#!v51jhTzB!AA4n7fH-ELM6PCssd0z89MewiJiVaK4rpS0BSjtnJHw
  * Second one is the same upload done using 10 threads without headercheck: https://mega.nz/#!bw1kHJBJ!0Yajf3EyYCS67sTMtjaT8ZHR54H-bTFOm7mvXK2thS8
  * Third one is again the same upload done using 10 threads + headercheck 30 sec after with 1 retry on the same server: https://mega.nz/#!Olk0lagK!K30WV-E7pqKmUAZQwkqZCcMWIox-7jybrQPvigjx-qY

* 5)
 * One thread: 7158 KBytes/Sec
 * 10 threads: 58065 KBytes/Sec

Thanks

**Comment by demanuel** [comment] 2016-01-08 21:05
What happens if you put 10 retries in the header check? Are the articles still missing?

Can you try the version that's on branch "issue22"?
I didn't perform any change that will solve this... Since i'm unable to reproduce it (i tried with small (20 megs) files only). I just improved the log. Basically:

If something happens that's not normal (this means a status code that isn't a 400 (session ended - xsnews has a timeout of 900 seconds (if an upload take more than 900 seconds the connections will die, and newsup will restart them)), 340, or 240, newsup will print the message returned by the server. 

If the issue happens without any out of normal message, please let me know the message-ids and the timestamp. I'll try to talk to xsnews support.

**Comment by kouze** [comment] 2016-01-10 19:56
Hi,

same issue if I put 10 retries for the header check. The last segment is still missing
http://pastebin.com/yRD5xPt4

```
~/bin/NewsUP/scripts/completion_checker.pl -nzb newsup.nzb | grep completed
File 9bde364f8adced06493979f74c766f86.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part01.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part02.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part03.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part04.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part05.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part06.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part07.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part08.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.part09.rar is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.sfv is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol00+01.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol01+02.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol03+04.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol07+08.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol15+16.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol31+32.par2 is 100.000000% completed
File 9bde364f8adced06493979f74c766f86.vol63+28.par2 is 96.551724% completed
```
```
223 0 <191452454868248944.C888VT1MEX@EAUOJZA5IO.newsup>
223 0 <201452454868248959.9OG2GM3NQ6@EAUOJZA5J3.newsup>
223 0 <291452454868249100.7HC902GF38@EAUOJZA5N0.newsup>
430 No such article.
File 9bde364f8adced06493979f74c766f86.vol63+28.par2 is 96.551724% completed
```
Here is the .nzb: https://mega.nz/#!Ho8TRYAT!Ki993oL241vznaTJCinchvZe7WLTSNjaYugzRh6QSNk

No particular message in the log as you can see in the pastebin upload log.

Thanks

**Comment by demanuel** [comment] 2016-01-10 20:52
Can you get me a timestamp when it was uploaded?

**Comment by kouze** [comment] 2016-01-10 22:14
Yes you are right, this one is missing
```
<segment bytes="768000" number="28">281452454868249084.8XMCPLUMYQ@EAUOJZA5MK.newsup</segment>
```

**Comment by demanuel** [comment] 2016-01-14 22:35
Can you try the latest version of issue22?

**Comment by kouze** [comment] 2016-01-15 12:34
Testing done: working fine now :)

```
time perl ~/bin/NewsUP/newsup.pl -f 9bde364f8adced06493979f74c766f86
Operation completed 510MB in 0m 10s. Avg. Speed: [52259 KBytes/Sec]
Warping up header check engines with 10 connections!
There are 0 segments missing
HeaderCheck done in 0m 25s
NZB newsup.nzb created!

real    0m34.709s
user    0m4.194s
sys     0m0.898s
```

I did the same test with 1 connection and the result is also good.

Thanks a lot for your fix :)

**Comment by demanuel** [comment] 2016-01-15 22:33
Awesome! Super! Thanks for your patience.

I just merge that version with the master.

Thanks for your testing.

Closing this.

**Closed by demanuel** 2016-01-15 22:33 UTC
Labels: enhancement
