### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by methanoid** [demanuel/NewsUP#72] opened 2019-05-02 13:39 UTC
Ubuntu 18.04 server. Followed Wiki install. Also made sure all dependencies present

Tried several times. Each time it completes script but if you ever type 
perl newsup.pl -file my_file -con 2 -news alt.binaries.test or similar it reports no such file (not unexpected cos I suspect docs wrong?)

If you try just newsup or permutations it reports: 
Initialization of state variables in list context currently forbidden at /usr/share/perl5/NewsUP/Utils.pm line 573, near ");"
Compilation failed in require at /usr/share/perl5/NewsUP/Article.pm line 5.
BEGIN failed--compilation aborted at /usr/share/perl5/NewsUP/Article.pm line 5.
Compilation failed in require at /usr/local/bin/newsup line 7.
BEGIN failed--compilation aborted at /usr/local/bin/newsup line 7.

Oh dear.. what to do?!

**Comment by demanuel** [comment] 2019-05-06 07:59
@methanoid,

Can you tell me what version of perl do you have installed? 

On commit bc5a73e8d99056f42b473022714a2de6458d46a5 i did some performance improvements that use the latest features available from perl. I believe that is the cause, as ubuntu doesn't have the latest perl available.

Can you replace your utils.pm with this one:https://raw.githubusercontent.com/demanuel/NewsUP/6ab7d4b91a461bc9ea16879ffb4adda9f62c3ed2/lib/NewsUP/Utils.pm ?

**Comment by methanoid** [comment] 2019-05-06 18:25
Thanks.  "This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
(with 67 registered patches, see perl -V for more detail)"

Where the heck does Utils.pm go?  Not /lib/NewsUP as there is no such dir.

**Comment by demanuel** [comment] 2019-05-07 22:19
hi.

I updated the ubuntu.sh script, please re-download it and run it, or you can just do:

`
curl -L https://raw.githubusercontent.com/demanuel/NewsUP/master/build_scripts/ubuntu/ubuntu.sh | bash
`

It contains several improvements and a patch for perl version 5.26. The patch, brings almost all performance improvements, except the ones i found problematic with version 5.26.

Please let me know if it fixed your issue.

BTW, I just checked and latest xubuntu version and it contains perl version 5.28

**Comment by demanuel** [comment] 2019-05-14 08:03
Changes caused by modifications done to improve performance.
This is fixed with the latest patch for ubuntu. Although it's fixed (for now) i urge to update to the latest stable perl.

**Closed by demanuel** 2019-05-14 08:03 UTC
Labels: compatibility
